### ISSUE TITLE
Would you ever make this 1.7.10 Forge compatable?

### ISSUE THREAD

**Issue by Sh3ddz** [brudin/Scooby#1]
I was wondering if you would ever make this 1.7.10 Forge compatable, or if that would be too much work. thanks!

**Comment by brudin** [comment]
I don't know.  How many servers are still on 1.7?

**Comment by 9vo** [comment]
All the real pvp servers are 1.7.10 he teams kohi badlion shotbow pleas make it 1.7.10

**Comment by 9vo** [comment]
Also can u change the knock back so u only take 3/4 of the knockback u would normaly get and make it so u deal more knockback

**Comment by brudin** [comment]
https://github.com/brudin/Scooby-1.7.10

Will have a compiled version up soon if all goes well...
