### ISSUE TITLE
Help Installing

### ISSUE THREAD

**Issue by corrupt3d** [brudin/Scooby#11]
How do i add this into my mods folder for 1.7.10 forge. Because when I download it it gives it to me as a .zip file instead of a jar file. also what is the key for triggerbot?

**Comment by 2sp00ky4u** [comment]
brudin if your reading this, the triggerbot doesnt work for me.

> Corrupt3d open the .zip file then you should get a .jar den you put it in your mods folder, and the triggerbot key is "R"

**Comment by corrupt3d** [comment]
when i open the winrar file it just shows another folder no .jar file

**Comment by brudin** [comment]
Triggerbot should work.  It currently only targets players.
Extract the zip file and there will be a jar inside, copy that to your mods folder.
This is a 1.8 mod so if you're installing it onto 1.7 forge you will run into problems.
