### ISSUE TITLE
Questions/ extras ;)

### ISSUE THREAD

**Issue by SaltyNips** [brudin/Scooby#2]
Hey! This is pretty swag thaat you made this open source! 
I have one question though, is this 100%bypassable on badlion, because I can't get banned ;p
Also you should add an aimbot as well that aims at the chest becasue everyone is asking for that :p
Pce <3

**Comment by 9vo** [comment]
Yes pleas do this pleassssssss and make it 1.7.10

**Comment by brudin** [comment]
This should bypass.  As of now, the only mod is a triggerbot, which will attack players at a random speed if your mouse is over them.
