### ISSUE TITLE
Can you please just upload the .jar file?

### ISSUE THREAD

**Issue by KRlSTOF** [brudin/Scooby#23]
I have tried every fucking way and program to extract it correctly but it keeps giveing me a FOLDER.
And i have installed mods before and extracted files before so i don't know what the heck am i doing wrong. So please give me a link the link .jar file!

**Comment by Rrwery** [comment]
Here is the 1.7.10 jar:
https://github.com/brudin/Scooby-1.7.10/releases/download/v0.1/Scooby.1.7.10.zip

And here it is for 1.8:
https://github.com/brudin/Scooby/releases/download/v0.2/Scooby.v0.2.1.8.zip
