### ISSUE TITLE
I NEED HELP DOWNLOADING 

### ISSUE THREAD

**Issue by lolyoubad** [brudin/Scooby#24]
pls fucking tell me how to download

**Comment by pokeball99** [comment]
No cursing good sir

**Comment by brudin** [comment]
https://github.com/brudin/Scooby/releases
This isn't rocket science.

**Comment by lolyoubad** [comment]
I have the download but what do i do from there?

**Comment by lolyoubad** [comment]
Do i just put in my forge mods folder?
