### ISSUE TITLE
Read----------->

### ISSUE THREAD

**Issue by lolyoubad** [brudin/Scooby#25]
Ok, so I really need help downloading this still. Someone pls tell me step by step what to do. Im not much of the computer guy or whatever. pce👌

**Comment by lolyoubad** [comment]
Pls tell me step by step and the links pls. Sorry if I look like a down

**Comment by lolyoubad** [comment]
Pls tell me step by step and the links pls. Sorry if I look like a down

**Comment by pokeball99** [comment]
FFS,stop Dat spam

**Comment by lolyoubad** [comment]
Sorry I need help

**Comment by pokeball99** [comment]
Just put it in your "mods" for Der after u have installed forge

**Comment by lolyoubad** [comment]
Wait

**Comment by lolyoubad** [comment]
List step by step. Like 
1. Download this (link) 
2. Do this

**Comment by lolyoubad** [comment]
Wait link what I put in my mods folder and that's it

**Comment by brudin** [comment]
Google how to install a Forge mod.

**Comment by pokeball99** [comment]
Needs a question label
