### ISSUE TITLE
no jar file? Need help.

### ISSUE THREAD

**Issue by corrupt3d** [brudin/Scooby#31]
Alright so when I download the zip file nothing, but a folder is inside. There is no jar file. 
![ss 2015-04-12 at 10 57 30](https://cloud.githubusercontent.com/assets/11512097/7106795/d39a46b6-e0fa-11e4-94c0-44ca16814058.png)
I know how to extract a file so dont tell me to learn how.
![ss 2015-04-12 at 10 58 25](https://cloud.githubusercontent.com/assets/11512097/7106797/de59d030-e0fa-11e4-84c3-1c22de5d3a92.jpg)
once it extracts it gives me a folder and inside the folder is another folder not a jar
![ss 2015-04-12 at 10 58 47](https://cloud.githubusercontent.com/assets/11512097/7106802/eaefa19e-e0fa-11e4-8af2-e93086439858.png)
and inside that folder is more and more folders. There isnt a jar inside.
Can you please help me solve my problem? Am i downloading the wrong file?

**Comment by brudin** [comment]
https://github.com/brudin/Scooby/releases
download Scooby.v0.2.1.8.zip
you're downloading the source code...
