### ISSUE TITLE
Add knockback multiplier

### ISSUE THREAD

**Issue by CircleStrafe** [brudin/Scooby#36]
Add a knock back multiplier where you can change how much knockback you take. For example if you want to take 0.6 blocks of knock back you can do that. I know cringed's ghost client has that (which I have) however it doesn't have an aim it like yours, so if you can add that it would be my favorite client

**Comment by eric-mcdonald** [comment]
Added a reduce velocity mod just now. Hopefully, brudin will accept my pull request, which should add it.

**Comment by brudin** [comment]
Check out @gunrun66's fork.
