### ISSUE TITLE
LOOL bad

### ISSUE THREAD

**Issue by SaltyNips** [brudin/Scooby#38]
Don't use this I got banned of kohi and badlion with it... I  had a shit load of logs

**Comment by brudin** [comment]
probably because you're only attacking when your mouse is over the player.  do some occasional misclicks or whatever.

this project is pretty much dead for now, check out @gunrun66's fork.

**Comment by eric-mcdonald** [comment]
@brudin my fork is also kind of dead for now (until exams and summatives are over). RIP.
