### ISSUE TITLE
Is it only 1.7.10 because hack forums says 1.8 but I installed on 1.9 FML and it didn't work

### ISSUE THREAD

**Issue by CaelanX** [brudin/Scooby#39]

**Comment by CaelanX** [comment]
Typo in title 1.8 not 1.9

**Comment by brudin** [comment]
1.8 version: https://github.com/brudin/Scooby
1.7.10 version: https://github.com/brudin/Scooby-1.7.10

Downloads for 1.8: https://github.com/brudin/Scooby/releases
They are in a zip format.  You need to extract the .jar file from the zip and put it in your mods folder.
