### ISSUE TITLE
@Brudin

### ISSUE THREAD

**Issue by CacaHuate** [brudin/Scooby#49]
Yoo my dude fucking sick source have been able to make a lot of different application for/with it but, I was wondering if you had any knowledge on how to make it so the mod doesn't register in the Forge Mod list so its a super ghost client. Thanks a lot for your time cheers!

**Comment by brudin** [comment]
I'm not entirely sure, maybe if you modify Forge itself this can be possible, or if you take an open source mod and just add the code to that.
