### ISSUE TITLE
t

### ISSUE THREAD

**Issue by FuckItAll** [brudin/Scooby#8]
When triggerbot is enabled you can run while hitting someone [not vary ghosty like]
could you change the sprint key

**Comment by brudin** [comment]
The sprint key is set to whatever you have it set to on Minecraft.  I'll fix the triggerbot right now.

**Comment by brudin** [comment]
Actually...
You can run while attacking in vanilla, even without mods.  I just tested in vanilla, while holding CTRL (or whatever you have sprint bound to), you can attack while sprinting.  Does NoCheat still alert for people attacking while sprinting?

**Comment by FuckItAll** [comment]
no it has no problems with nocheat i just thought it didn't seem legit
